services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11500:11434" # NOTE: local環境に入れていると、11434ポートが使えないため11500にマッピング
    volumes:
      - ollama-data:/root/.ollama
    command: ["serve"]

  mcp-server:
    build: .
    container_name: mcp-server
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    env_file:
      - .env 
    develop:
      watch:
        - path: ./
          action: sync
          target: /app
        - path: ./
          action: rebuild

volumes:
  ollama-data:
