services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11500:11434"
    volumes:
      - ollama-data:/root/.ollama
    command: ["serve"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  mcp-server:
    build: .
    container_name: mcp-server
    ports:
      - "4000:4000"
    depends_on:
      - ollama
    env_file:
      - .env 
    develop:
      watch:
        - path: ./ 
          action: sync
          target: /app
        - path: ./ 
          action: rebuild

volumes:
  ollama-data:
