services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11500:11434" # NOTE: local環境に入れていると、11434ポートが使えないため11500にマッピング
    volumes:
      - ollama-data:/root/.ollama
    command: ["serve"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-0}   # 0ならGPU割り当てなし
              capabilities: [gpu]
    runtime: nvidia

  mcp-server:
    build: .
    container_name: mcp-server
    ports:
      - "4000:4000"
    depends_on:
      - ollama
    env_file:
      - .env 
    develop:
      watch:
        - path: ./
          action: sync
          target: /app
        - path: ./
          action: rebuild

volumes:
  ollama-data:
