services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11500:11434"
    volumes:
      - ollama-data:/root/.ollama
    command: ["serve"]

  mcp-server:
    build: .
    container_name: mcp-server
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    develop:
      watch:
        - path: ./
          action: sync
          target: /app
        - path: ./
          action: rebuild


volumes:
  ollama-data:
